---

- name: Network Getting Started First Playbook
  connection: network_cli
  gather_facts: false
  hosts: all
  vars:
    ansible_network_os: ios
  tasks:

    - name: Get config for Ios devices
      ios_facts:
        gather_subset: all

    - name: Display the config
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"
